name: VotePoints
main: JD\RankPoints\Main
version: 1.5.3
api: [3.0.0]
author: ServerMaker
load: POSTWORLD
commands:
  votepoints:
    description: "Shows/Gives vote Points"
    aliases: [vp]
    usage: "/votepoints {player points}"
    
    
